const select = data => data.data[Math.floor(Math.random() * data.data.length)];
const cookie = [
	'With integrity and consistency -- your credits are piling up.',
	'Reach out your hand today to support others who need you.',
	'It is not the outside riches bit the inside ones that produce happiness.',
	'How dark is dark?, How wise is wise?',
	'We can admire all we see, but we can only pick one.',
	'The man who has no imagination has no wings.',
	"To courageously shoulder the responsibility of one's mistake is character.",
	"We can't help everyone. But everyone can help someone.",
	'You discover treasures where others see nothing unusual.',
	'Make all you can, save all you can, give all you can.',
	'Understanding the nature of change, changes the nature.',
	'You will be unusually successful in business.',
	'Your spirit of adventure leads you down an exiting new path.',
	'Genius is one percent inspiration and ninety-nine percent perspiration.',
	'You are the master of every situation.',
	'Be brave enough to live creatively.',
	'Cookies go stake. Fortunes are forever.',
	'Your ingenuity and imagination will get results.',
	'Unnecessary possessions are unnecessary burdens.',
	'Ability is not something to be shown off.',
	'If you wish to see the best in others, show the best of yourself.',
	'Your power is in your ability to decide.',
	'Wherever you go, whenever you can, try to leave a gift.',
	'Kind words can be shot and easy to speak, but their echoes are truly endless.',
	'Your ingenuity and imagination will get results.',
	'Age can never hope to with you while your heart is young.',
	'Example is better than perception.',
	'Idleness is the holiday of fools.',
	"Don't be pushed by your problems. Be led by your dreams.",
	'Many receive advice, only the wise profit from it.',
	'You will have good luck and overcome many hardships.',
	'A good way to keep healthy is to eat more Chinese food.',
	"Today's profits are yesterday's good well ripened.",
	'LSDBS - Let Something Good Be Said.',
	'There is in the worst of fortunes the best change of a happy ending.',
	'Service to many leads to greatness.',
	'Desire, like the atom, is explosive with creative force.',
	'I think and that is all that I am.',
	'Judge each day not by the harvest you reap but by the seeds you plant.',
	'Yesterday was a dare to struggle. Today is a dare to win.',
	'Make everyday your best. You will improve yourself greatly.',
	'You must be willing to act today in order to succeed.',
	'Venture not all in one boat.',
	'Suppressing a moment of anger may save a day of sorrow.',
	'Never be less than your dreams.',
	'The good times start when I count to 3: 1... 2... 3.',
	'An inch of time is an inch of gold.',
	'If you chase two rabbits both will escape.',
	'You will soon be surrounded by good friends and laughter.',
	'Haste does not bring success.',
	'You will stumble into the path that will lead your life to happiness.',
	'You will always be successful in you professional career.',
	'Good news will come to you from far away.',
	'Service is the rent you pay for having room on the Earth.',
	'Be smart, but never show it.',
	'The only certainty is that nothing is certain.',
	'You or a close friend will be married soon.',
	"We will not know the worth of water 'till the well is dry.",
	'You are talented in many ways.',
	'Do your best to make it happen',
	'You will find great forces in unexpected places.',
	'What you see in the mirror, and what you are can be two different images.',
	'Excuses are easy to manufacture, and hard to sell.',
	'Do onto others as you wish others do onto you.',
	'Struggle as and hard as you can for whatever you believe in.',
	'You have a pair of shining eyes.',
	'You should be able to undertake and complete anything.',
	'Your principles mean more to you than any money or success.',
	'Forgiveness does not change the past, but it does enlarge the future.',
	"Stand tall! Don't look down upon yourself.",
	'Every truly great accomplishment is at first impossible.',
	'Courage is not the absence of fear; it is the conquest of it.',
	'Wise man seldom talks.',
	"If you have a job without aggravations, you don't have a job.",
	'You are broad minded and socially active.',
	"Don't put off till tomorrow what can be enjoyed today.",
	'A family reunion in the coming months will be a tremendous success!',
	'Enthusiastic leadership gets you a promotion when you least expect it.',
	'Calamity is the touchstone of a brave mind.',
	'Everything you add to the truth subtracts from the truth.',
	'You are going to take a vacation.',
	'Commitment is the stuff character is made of; the power to change the face of things.',
	'A friend asks only for your time not your money.',
	'A friend asks only for your time not your money.',
	'A handful of patience is worth more than a bushel of brains.',
	'A handful of patience is worth more than a bushel of brains.',
	'To be eighty years young is more cheerful and hopeful than forty years old.',
	'To be eighty years young is more cheerful and hopeful than forty years old.',
	'A person is not wise simply because one talks a lot.',
	'It takes guts to get out of the ruts.',
	'The greatest quality is seeking to serve others.',
	'Most people, once they graduate from the school of Hard Knocks, automatically enroll.',
	'Everyone needs to be loved, especially those do not deserve it.',
	"Winning isn't everything but the will to win is.",
	'You display the wonderful traits of charm and courtesy.',
	'You will be awarded some great honor.',
	"Don't build your happiness on other's sorrow.",
	'The best thing about growing older is that it takes such a long time.',
	'You have a deep interest in all that is artistic.',
	'Kiss is not a kiss without the heart.',
	"Don't be afraid of fear.",
	"There's no point to being grown up if you can't be childish sometimes.",
	'You will learn something new every day.',
	"You can't go far in a rowboat without oars.",
	'Failure is the virtual way to prepare you for great responsibilities.',
	'Many receive advice only the wise profit by it.',
	'A banker is someone who lends you an umbrella when the sun is shining.',
	'Maturity: Do your duty without being supervised.',
	'Your cheerful outlook is one of your assets.',
	"You can't have everything... where would you put it all?",
	'You have an unusually magnetic personality.',
	'You have an unusually magnetic personality.',
	'He who hurries cannot walk with dignity.',
	'You never hesitate to tackle the most difficult problems.',
	'Your emotional nature is strong and sensitive.',
	'Serious trouble will bypass you.',
	"If you're riding ahead of the heard, look back once in a while to make sure it's still there.",
	'You have an iron will, which helps you succeed in everything.',
	'Three can keep a secret if you get rid of two.',
	'Everywhere you choose to go friendly faces will greet you.',
	'Nothing gets in the way of your vision of yourself in the future.',
	'To understand is hard. Once one understands, action is easy.',
	'The philosophy of one century is the common sense of the next.',
	'You will make many changes before settling satisfactorily.',
	'When in anger, sing the alphabet.',
	'Wealth is a means to an end... not the end itself.',
	"It's high time for one of your most promising ideas.",
	'Small opportunities are often the beginning of great enterprises.',
	'People are drawn to you and look to you for advice.',
	'Keep your feet on the ground even though friends flatter you.',
	'Do a good deed anonymously. You will make a difference in your life.',
	'Financial prosperity is coming your way!',
	'A healthy body will benefit you forever.',
	'Mental activity keeps you busy at this time.',
	"Say \"I love you\" and mean it. You can't do that enough.",
	'The world is always ready to receive talent with open arms.',
	'Enjoy the small things you find on your path.',
	'Good food brings good health and longevity.',
	'The act of giving is more important than receiving.',
	'Every burden is a blessing.',
	'Prosperity is in your fortune.',
	'Your next interview will result in a job.',
	'Accept the challenges, so that you may feel the exhilaration of victory.',
	'The future belongs to those who believe in the beauty of their dreams.',
	'Peace begins with a smile.',
	'Engage in group activities that further transformation.',
	'Be satisfied with what you already own.',
	'Your business will assume vast proportions.',
	'You have a potential urge and the ability for accomplishment.',
	'People find it difficult to resist your persuasive manner.',
	"Action is worry's worst enemy.",
	'Men do not fail... they give up trying.',
	"Are your legs tired? You been running through someone's mind ALL day long.",
	'You find beauty in ordinary things. Do not loose this ability.',
	'Will you let compassion to manage your wishes.',
	'A truly great person never puts away the simplicity of a child.',
	'Home is where your heart is.',
	'A huge fortune at home is not as good as money in use.',
	'Humor is the affirmation of dignity.',
	'Your heavy desire, only allow you to see what you are looking for.',
	'TEAMS - Together Everyone Achieves More Success.',
	'You have a heart of gold.',
	'Life to you is a bold and dashing responsibility.',
	'Want to learn how to love, start with the one you hate.',
	'There is beauty in simplicity.',
	'Learning is a treasure which accompanies us everywhere.',
	'It is much easier to be critical than to be correct.',
	"This person's love is just and true. You may rely on it.",
	'You will be spending time outdoors, in the mountains, near water.',
	'Friends long absent are coming back to you.',
	'He joyfulness of a man prolongeth his days.',
	'Regenerate your system through diet and exercise. Save the cookies!',
	'Listen to the wisdom of the old.',
	'Even the toughest of days have bright spots, just do your best.',
	'Your talents will be recognized and suitably rewarded.',
	'Fortitude is the guard and support of the other virtues.',
	'When the moment comes, take the one from the right.',
	'Old friends make best friends.',
	'You have an ability to sense and know higher truth.',
	'People learn little from success, but much from failure.',
	'Keep in mind your most cherished dreams of the future.',
	'You always do things the right way.',
	'Act boldly and unseen forces will come to your aid.',
	"Join a new club today, you'll be surprised.",
	'Your many hidden talents will become obvious to those around you.',
	'Some people never have anything except ideas, Go do it.',
	'A real patriot is the fellow who gets a parking ticket and rejoices that the system works.',
	'You are more likely to give than give in.',
	'If you bite the hand that feeds you, it wont taste as good as the food you were fed.',
	'The heart has its reasons, which the reasons dos not know.',
	'Even the longest of days will come to an end.',
	'You enjoy giving gifts of yourself to others, you will be rewarded!',
	'There are no stupid questions, just stupid answer.',
	'Success is an accumulation of successful days.',
	'You have a friendly heart and are well admired.',
	'Just because you put tap shoes on an elephant does not mean it can dance.',
	'Start to look for you faults if you never made mistakes.',
	'Good sense is the master of human life.',
	'Your luck has been completely changed today.',
	'Ask advice, but use your own common sense.',
	'A judgment will rule in your favor.',
	'Your winsome smile will be your sure protection.',
	'Go confidently in the direction of your dreams.',
	'The skills you have gathered will one day come in handy.',
	'Look forward to great fortune and a new lease on life!',
	'You will travel to many places.',
	'You will enjoy a trip to Asia.',
	'Better to do something imperfectly than to do nothing perfectly.',
	'Pure logic is the ruin of the spirit.',
	'You will have a long and wealthy life.',
	'Your smile always brightens the cloudiest days.',
	'A friend in the market is better than money in the purse.',
	'A new venture will be a success.',
	'It is by those who have suffered that the world is most advanced.',
	'Everything must have a beginning.',
	'The important thing is to express yourself.',
	'The real meaning of enlightenment is to gaze with undimmed eyes on all undimmed.',
	'New and rewarding opportunities will soon develop for you.',
	'Seek to assert your devotion when a worthy situation arises.',
	"The glass is not half-empty, it's just twice too big.",
	'A feeling is an idea with roots.',
	'Your present plans are going to succeed.',
	'A sound mind and healthy body bring many happy events to your family.',
	'Plan your work and work your plan.',
	'Courage is rightly considered the foremost of the virtues, for upon it, all others depend.',
	'Say hello to others. You will have a happier day.',
	"Don't let your limitations overshadow your talents.",
	'Love is the affinity which links and draws together the elements of the world.',
	'You should be able to undertake and complete anything.',
	'Character development is the true aim  of education.',
	'Trust him, but sill keep your eyes open.',
	'He who is shipwrecked the second time cannot lay the blame on Neptune.',
	'To get respect from others, one must first give respect to others.',
	'Walk the words you talk and talk the words you walk.',
	'People forget how fast you did a job - but they remember how well you did it.',
	'The time is right to make new friends.',
	'Do what is right, not what you should.',
	'Punctuality is the politeness of kings and the duty of gentle people everywhere.',
	'If you wait too long for the perfect moment, the perfect moment will pass you by.',
	'Your heart is pure, and your mind clear, and soul devout.',
	'Walk with a good heart and you will run with success.',
	'We should not let our fears hold us back from pursuing our hopes.',
	'Do not mistake temptation for opportunity.',
	'You will soon meet the person you admire.',
	'A good time to start something new.',
	'All generalities are false.',
	'Come back later... I am sleeping. (yes, cookies need their sleep too)',
	'If at first you do not succeed... try something harder.',
	'Your good listening skills will open many doors.',
	'Two people shorten a road.',
	'Stop waiting! Buy that ticket take that special trip!',
	'A problem clearly stated is a problem half solved.',
	'Accept your independence and use it wisely.',
	'May the warm winds of heaven blow softly upon your sprint.'
];
const proverb = [
	"A friend's frown is better than a fool's smile.",
	'A friend in need is a friend indeed.',
	'A friend is easier lost than found.',
	'A friend to everybody is a friend to nobody.',
	'A problem shared is a problem halved.',
	'A true friend is someone who reaches for your hand, but touches your heart.',
	'False friends are worse than open enemies.',
	"Flattery is all right so long as you don't inhale.",
	'Give credit where credit is due.',
	'Grief divided is made lighter.',
	'Memory is the treasure of the mind.',
	'Nothing dries sooner than a tear.',
	'Old friends and old wine are best.',
	'The best of friends must part.',
	'The best things are not bought and sold.',
	'There is no better looking-glass than an old friend.',
	'To err is human (To forgive divine).',
	'Two cannot fall out if one does not choose.',
	'A loveless life is a living death.',
	'Absence makes the heart grow fonder.',
	"All's fair in love and war.",
	'Beauty is in the eye of the beholder.',
	'Before you meet the handsome prince you have to kiss a lot of toads.',
	'Better to have loved and lost, than to have never loved at all.',
	'Cold hands, warm heart.',
	'Distance makes the heart grow fonder.',
	'Faint heart never won fair lady.',
	'First impressions are the most lasting.',
	'Hatred is as blind as love.',
	'Love and a cough cannot be hid.',
	'Love does much but money does all.',
	'Love levels all inequalities.',
	'Love makes a good eye squint.',
	'Love sees no faults.',
	'Love sought is good, but given unsought is better.',
	'Love to live and live to love.',
	'Love with life is heaven; and life unloving, hell.',
	'Man is the head but woman turns it.',
	'Marry in haste, repent at leisure.',
	'The course of love never did run smooth.',
	'The Lord loveth a cheerful liar.',
	'There is a thin line between love and hate.',
	"To eat one's heart out.",
	'True beauty lies within.',
	"You can't live on bread alone.",
	"A good friend is one's nearest relation.",
	'A man is known by the company he keeps.',
	'A man of straw needs a woman of gold.',
	'A wink is as good as a nod, to a blind man.',
	'An injury is forgiven better than an injury revenged.',
	'Anger and hate hinder good counsel.',
	'Appearances are deceptive.',
	"At a round table there's no dispute about the place.",
	'Attack is the best form of defense',
	'Be slow in choosing, but slower in changing.',
	'Behind every great man stands a strong woman.',
	'Blood is thicker than water.',
	'Cheerfulness smooths the road of life.',
	'Confess and be hanged.',
	'Conscience makes cowards of us all.',
	"Don't blow your own trumpet.",
	'Do as you would be done by.',
	'Do unto others as you would have them do to you.',
	"Grow angry slowly; there's plenty of time.",
	'He bears misery best that hides it most.',
	'He that hurts another, hurts himself.',
	'He who wronged you will hate you.',
	'Heavy givers are light complainers.',
	'I am rubber and you are glue. Your words bounce off me and stick to you.',
	"If you lose your temper, don't look for it.",
	"It's not over till it's over.",
	'Joy shared is double joy; grief shared is (only) half grief.',
	'Laugh and the world laughs with you. Cry and you cry alone.',
	'Never let the sun set on angry heart.',
	'Never let the sun go down on your anger.',
	'Never let the sun set on thy wrath.',
	"Never quarrel with one's bread and butter.",
	"No man or woman is worth your tears, and the one who is, won't make you cry.",
	'Open confession is good for the soul.',
	'Out of sight, out of mind.',
	'Patience is a virtue.',
	'Persuasion is better than force.',
	'Spare the rod and spoil the child.',
	'Temper is so good a thing that we should never lose it.',
	'To the world you may be one person, but to one person, you may be the world.',
	'Wondrous is the strength of cheerfulness.',
	'You made your bed, now you must lie in it.',
	'A bully is always a coward.',
	'A handsome shoe often pinches the foot.',
	'A good thing is all the sweeter when won with pain.',
	'A man too careful of danger lives in continual torment.',
	'A miss is as good as a mile.',
	'Adversity flatters no man',
	'Adversity and loss make a man wise',
	'All promises are either broken or kept.',
	'All things come to those that wait.',
	'An eye for an eye and a tooth for a tooth.',
	'An open door may tempt a saint.',
	'As one door closes, another always opens.',
	'As you go through life, make this your goal, watch the doughnut and not the hole.',
	'Brevity is the soul of wit.',
	'Cut your coat according to the cloth.',
	'Discretion is the better part of valour.',
	'Do right and fear no man.',
	'Easy come, easy go.',
	'Experience is the hardest teacher. She gives the test first and the lesson afterwards.',
	'Familiarity breeds contempt.',
	'Fortune favours the brave.',
	'Hall binks are oft sliddery.',
	'He who laughs last, laughs longest.',
	'Home is where the heart is.',
	'Hope for the best and prepare for the worst.',
	'If wishes were horses, beggars would ride.',
	'In the country of the blind, the one-eyed man is king.',
	'It never rains but it pours.',
	'Leave tomorrow till tomorrow.',
	'Life begins at forty.',
	'Lifes trials may be hard to bear, but patience can outlive them.',
	'Live and learn.',
	'Manners maketh the man.',
	'No man is worse for knowing the worst of himself.',
	'Only the good die young.',
	'Procrastination is the thief of time.',
	'The best things in life are free.',
	'The family that prays together, stays together.',
	'The longer you live the more you see.',
	'The meek shall inherit the earth.',
	'The receiver is as bad as the thief.',
	'To wait and be patient soothes many a pang.',
	"Up and down like a fiddler's elbow.",
	'We cannot erase the sad records from our past.',
	"What the eye doesn't see, the heart doesn't grieve over.",
	"While there's life there's hope.",
	'After dinner rest a while, after supper walk a mile.',
	'An apple a day keeps the doctor away.',
	'A drowning man will clutch at a straw.',
	'An onion a day keeps everyone away.',
	'Another pot ! Try the teapot.',
	'As fit as a fiddle.',
	'As hard as nails.',
	'As sick as a dog.',
	'As you go through life, make this your goal, watch the doughnut and not the hole.',
	'Be not a baker if your head is made of butter.',
	'Beauty is but skin deep.',
	'Better late thrive than never do well.',
	'Better to be poor and healthy rather than rich and sick.',
	'Better to wear out than rust out.',
	'Bread never falls but on its buttered side.',
	'Cleanliness is next to Godliness.',
	'Content is health to the sick and riches to the poor.',
	"Don't bite the hand that feeds you.",
	'Drink like a fish, water only.',
	'Early to bed, early to rise, makes you healthy, wealthy & wise.',
	'Fair words butter no cabbage.',
	'Good wine ruins the purse, and bad wine ruins the stomach.',
	'Greediness burst the bag.',
	'Grumbling makes the loaf no larger.',
	'Half a loaf is better than none.',
	'He who drinks a little too much drinks much too much.',
	'He who rises late must trot all day.',
	'His eyes are bigger than his belly.',
	'Hunger is the best sauce.',
	'It is no use crying over spilt milk.',
	'Old friends and old wine are best.',
	"One man's meat is another man's poison.",
	'Ready money is ready medicine.',
	'Sound as a bell.',
	'The nearer the bone the sweeter the meat.',
	'The proof of the pudding is in the eating.',
	"There's many a slip, twixt cup and the lip.",
	'To add insult to injury.',
	'To look as if butter will not melt in his mouth.',
	'Too many cooks spoil the broth.',
	"What can't be cured must be endured.",
	'What you eat today walks and talks tomorrow.',
	'You are what you eat.',
	"You can't have your cake and eat it too.",
	'You can eat an elephant if you do it one mouthful at a time.',
	"You can't unscramble a scrambled egg.",
	'Wondrous is the strength of cheerfulness.',
	'A fool uttereth all his mind.',
	'A bad excuse is better then none.',
	'Actions speak louder than words.',
	'Angry words fan the fire like wind.',
	'Bad news travels fast.',
	'Call a spade a spade.',
	'Do as I say not as I do.',
	"Don't advertise: Tell it to a gossip.",
	"Don't go off half-cocked.",
	'Few words and many deeds.',
	"For donkeys' ages.",
	'Gossips are frogs, they drink and talk.',
	'He who sings drives away sorrow.',
	"If you don't say it you will not have to unsay it.",
	'It takes two to have an argument.',
	'Keep your mouth shut and your eyes open.',
	'Listen to the pot calling the kettle black.',
	'Many a true word spoken in jest.',
	'No news is good news.',
	'Nothing is ill said if it is not ill taken.',
	'One picture is worth a thousand words.',
	'Say what you mean and mean what you say.',
	'Self praise is no recomendation.',
	'Silence is an excellent remedy against slander.',
	'Silence is golden.',
	'Silence is less injurious than a bad reply.',
	'Since before cocky was an egg.',
	'Speak clearly, if you speak at all.',
	'Sticks and stones may break my bones but words will never hurt me.',
	'Stop beating around the bush.',
	"Take your wife's first advice.",
	'Talking comes by nature, silence by wisdom.',
	'A change is as good as a rest.',
	'A stitch in time saves nine.',
	'A throne is only a bench covered in purple velvet.',
	'A wise man shall hold his tongue till he sees his opportunity.',
	'Accidents will happen.',
	"All's well that ends well.",
	'Attack is the best means of defence.',
	'Charity begins at home.',
	'Different strokes for different folks.',
	'Do not in an instant what an age cannot recompense.',
	"Don't knock on death's door, ring the doorbell and run.",
	"Don't try to teach your grand-mother to suck eggs.",
	'Empty vessels make the most sound.',
	'Empty barrels make the most noise.',
	'Four eyes are better than two.',
	'He who fights and runs away, lives to fight another day.',
	'Innocent as a new born babe.',
	"It's an ill wind that blows no-one some good.",
	"It is better to stay silent and be thought a fool, than to open one's mouth and remove all doubt.",
	'Necessity is the mother of invention.',
	'No one can be caught in places he does not visit.',
	'No wise man ever wishes to be younger.',
	'Not in a month of Sundays.',
	"One mans junk is another man's treasure.",
	'Out of the frying pan into the fire.',
	'Show a clean pair of heels.',
	'Still waters run deep.',
	'The darkest hour is before the dawn.',
	'The wise shall understand.',
	"Those who don't learn from history are doomed to repeat it.",
	'Tomorrow is a new day.',
	'Two heads are better than one.',
	"You can't tell a book by its cover.",
	'Where observation is concerned, chance favours only the prepared mind.',
	"Where there's smoke there's fire.",
	'Wisdom is better than strength.',
	'Wisdom is neither inheritance nor a legacy.',
	'Wisdom is the wealth of the wise.',
	'Wise it is to comprehend the whole.',
	"You can't put an old head on young shoulders.",
	'You never know what you can do till you try.',
	"Once a task has first begun, never quit until it's done,",
	'be the labour great or small, do it well or not at all.',
	'A bad workman blames his tools',
	'A good reputation is a fair estate.',
	'All work and no play makes Jack a dull boy.',
	"An idle man is the devil's playfellow.",
	'Diligence is the mother of good luck.',
	"Don't try kicking against the wind.",
	'Everybody must row with the oars he has.',
	'Hard work never did anyone any harm.',
	'If a job is worth doing it is worth doing well.',
	"If at first you don't succeed, try, try again.",
	"If you can't help, don't hinder.",
	'If you see something you like, take it and make it better.',
	"It's all in a days work.",
	'Laziness travels so slowly that poverty soon overtakes it.',
	'Least talk most work.',
	'Many hands make light work.',
	'More haste less speed.',
	'Needs must when the devil drives.',
	"Never put off 'til tomorrow what you can do today.",
	'No life can be dreary when work is a delight.',
	'Not to break is better than to mend.',
	'The devil finds work for idle hands.',
	'The harder you work, the luckier you are.',
	'The hardest work is to do nothing.',
	'A bird in the hand is worth two in the bush.',
	'A bird makes his nest little by little.',
	'A cat has nine lives.',
	'All cats are grey in the dark.',
	'An elephant never forgets.',
	'An old fox need learn no craft.',
	'Birds of a feather flock together.',
	'Curiosity killed the cat; Satisfaction brought it back.',
	'Curses, like chickens come home to roost.',
	"Don't count your chickens before they hatch.",
	'Every dog has its day.',
	'His bark is louder than his bite.',
	"If you lie down with dogs, you'll get up with fleas.",
	"It's an ill bird that fouls its own nest.",
	"It's an old dog for a hard road.",
	"It's no use closing the stable door, after the horse has bolted.",
	'Kill two birds with the one stone.',
	'Let sleeping dogs lie.',
	'Like a fish out of water.',
	'Never look a gift horse in the mouth.',
	'No sense closing the barn door after the horse has bolted.',
	'Nothing falls into the mouth of a sleeping fox.',
	'Putting the cart before the horse.',
	'Sauce for the goose is sauce for the gander.',
	'The early bird catches the worm.',
	'The leopard does not change his spots.',
	'The sleepy fox catches no chickens.',
	"There's no use in flogging a dead horse.",
	'To scare a bird is not the way to catch it.',
	'What do you expect from a pig, but a grunt?',
	'When a fox hears a rabbit screaming it comes running, but not to help.',
	'While the cats away the mice play.',
	"You can lead a horse to water, but you can't make him drink.",
	"You can't make a silk purse out of a sow's ear.",
	'A chain is no stronger than its weakest link.',
	'A rolling stone gathers no moss.',
	'After the storm comes the calm.',
	"All aren't hunters that blow the horn.",
	'As green as grass.',
	'As is the gardener so is the garden.',
	'As you sow, so shall you reap.',
	"Best to bend it while it's a twig.",
	'Better to go back than go wrong.',
	'By hook or by crook.',
	'Deeds are fruits, words are but leaves.',
	'Distance lends enhancement to the view.',
	"Don't count your chickens before they are hatched.",
	"Don't cross your bridges until you come to them.",
	'Empty bags cannot stand upright.',
	'Every cloud has a silver lining.',
	'Every path has its puddle.',
	'Fresh as a daisy.',
	'Good company on the road is the shortest cut.',
	'It is better to be green and growing than ripe and rotten.',
	'Leave no stone unturned.',
	'Like looking for a needle in a haystack.',
	'Make hay while the sun shines.',
	"Milk the cow but don't pull off the udder.",
	'Never cackle unless you lay.',
	'Oaks may fall when reeds take the storm.',
	'Shake the hand before you plough the field.',
	"Strike while the iron's hot.",
	'The beaten path is safest.',
	'The best ground bears weeds as well as flowers.',
	'The grass is always greener on the other side of the fence.',
	'The longest journey begins with the first step.',
	'The longest way round is the sweetest way home.',
	'The more you stir, the more it stinks.',
	'The sun shines on both sides of the hedge.',
	'The worst wheel always creaks most.',
	'Too many irons in the fire.',
	'Useless as a screen door on a dunny.',
	"You can't get blood out of a stone.",
	'A little body doth often harbour a great soul.',
	'A point is the beginning of magnitude.',
	'A spark can start a great fire.',
	'A short cut is often a wrong cut.',
	'Big fish eat little fish.',
	'Everything has an end.',
	'Fall seven times. Stand up eight.',
	'First in best dressed.',
	'From trivial things, great contests often arise.',
	"Give them an inch and they'll take a mile.",
	"Grow angry slowly, there's plenty of time.",
	'He who hesitates is lost.',
	"It's either all or nothing.",
	'It is easier to destroy than to build.',
	'It is the first step that is difficult.',
	'Little strokes fell great oaks.',
	'Lost time is never found again.',
	'Many drops make a shower.',
	'Mighty oaks from tiny acorns grow.',
	'Necessity is a hard nurse, but she raises strong children.',
	"Rome wasn't built in a day.",
	'Seize the day',
	'Small faults indulged let in greater.',
	'Some of the best gifts come in small packages.',
	'Step by step one goes far.',
	'You have to crawl before you walk.',
	"Find a coin pick it up, All the day you'll have good luck. Drop a penny leave it lay, Bring someone a lucky day.",
	'A bad penny always comes back.',
	'A light purse makes a heavy heart.',
	'A little each day is much in a year.',
	"A man's intentions seldom add to his income.",
	'A penny saved is a penny earned.',
	'A poor man is better than a liar.',
	'A single penny fairly got is worth a thousand that are not.',
	'Always you are to be rich next year.',
	"Beggars can't be choosers.",
	'Better to have than to wish.',
	'Diamonds are forever.',
	'Every man has his price.',
	'Every man is the architect of his destiny.',
	'Experience is the father of wisdom.',
	'Fair exchange is no robbery.',
	'He has enough who is content.',
	'He that pays last never pays twice.',
	'He is rich that is satisfied.',
	'In for a penny, in for a pound.',
	'It is better to be born lucky than rich.',
	'Little and often fill the purse.',
	'Little thieves are hanged, but great ones escape.',
	'Money burns a hole in your pocket.',
	'Never spend your money before you have it.',
	'One today is worth two tomorrows.',
	'Penny wise, pound foolish.',
	'Take care of the pence and the pounds will take care of themselves.',
	'The best cast at dice is not to play.',
	'The love of money is the root of all evil.',
	'There is no honour among thieves.',
	'Waste not, want not.',
	'A good conscience is a soft pillow.',
	'A good thing is soon snatched up.',
	'A little knowledge is a dangerous thing.',
	'Better safe than sorry.',
	'Better late than never.',
	'Business before pleasure.',
	'Credit won by lying is quick in dying.',
	'Damage suffered makes you knowing, but seldom rich.',
	'Desperate diseases must have desperate remedies.',
	'Divide and conquer.',
	"Don't rely on the label on the bag.",
	"Don't throw the baby out with the bath-water.",
	"Don't put all your eggs in one basket.",
	'Experience is the best teacher.',
	'First come, first served.',
	'Fore-warned is fore-armed.',
	'Hasty climbers have sudden falls.',
	'Hasty judgements are generally faulty.',
	'Honesty is the best policy.',
	'If anything can go wrong, it will.',
	"If you don't know where you're going, then the journey is never ending.",
	"It's a poor job that can't carry one boss.",
	'Keep It Simple (The KISS principal).',
	'Let the buyer beware.',
	'Look before you leap.',
	'Nobody can serve two masters.',
	'One false move may lose the game.',
	"One man's loss, is another man's gain.",
	'Peace begins just where ambition ends.',
	'Possession is nine tenths of the law.',
	'Rules are made to be broken.',
	'The customer is always right.',
	'The gods help them that help themselves.',
	'The golden age never was the present one.',
	'To each his own.',
	'We do not always gain by changing.',
	"Where there's a will there's a way.",
	'A fool and his money are soon parted.',
	'A fool in a gown is none the wiser.',
	"A wise man doesn't need advice, and a fool won't take it.",
	'Advice when most needed is least heeded.',
	'Always in a hurry, always behind.',
	'Cheap is dear in the long run.',
	'Confess and be hanged.',
	"Cut off one's nose to spite one's face.",
	'Empty vessels make the most noise.',
	'Facts do not cease to exist because they are ignored.',
	'Fools rush in where angels fear to tread.',
	"He who won't be advised, can't be helped.",
	'If the cap fits, wear it.',
	'In one ear and out the other.',
	"It can't happen here is number one on the list of famous last words.",
	"It is better to stay silent and be thought a fool, than to open one's mouth and remove all doubt.",
	'One of these days is none of these days.',
	'Pride cometh before a fall.',
	'Pride feels no pain.',
	'See nothing, say nothing, know nothing.',
	'The bigger they are the harder they fall.',
	'The fool wanders, the wise man travels.',
	'The hood does not make the monk.',
	'The wise man is deceived once but the fool twice.',
	'There is no fool like an old fool.',
	'Use not today what tomorrow will need.',
	"What's the good of home, if you are never in it?",
	'You cannot lose what you never had.',
	'The pen is mightier than the sword.',
	'Actions speak louder than words.',
	'Many hands make light work.',
	'Too many cooks spoil the broth.',
	"You're never too old to learn.",
	"You can't teach an old dog new tricks.",
	'Ask no questions and hear no lies.',
	'Ask and you shall receive.',
	'Variety is the spice of life.',
	"Don't change horses in midstream.",
	"Don't cross the bridge till you come to it.",
	'Forewarned is forearmed.',
	'Silence is golden.',
	'The squeaky wheel gets the grease.',
	'Clothes make the man.',
	'Never judge a book by its cover',
	'The best things come in small packages.',
	'The bigger, the better.',
	'A miss is as good as a mile.',
	'Half a loaf is better than none.',
	'Look before you leap.',
	'He who hesitates is lost.',
	"If at first you don't succeed, try, try again.",
	"Don't beat a dead horse.",
	'The early bird gets the worm.',
	'The second mouse gets the cheese.',
	'Absence makes the fond heart wander.',
	'Change is inevitable, except from vending machines.',
	"Eagles may soar, but weasels don't get sucked into jet engines.",
	"Everyone has a photographic memory, some just don't have film.",
	"If it's not broken, don't fix it.",
	"If it's not broke, mess with it till it is.",
	'It is lonesome in the saddle since the horse died.',
	'The lights on, but nobodies home.',
	'The strongest memory is weaker than the palest ink.',
	'A burden in the bush is worth two in the hand.',
	'A journey of a thousand sites begins with a single click.',
	'C:\\ is the root of all Windows directories.',
	"Don't byte off more than you can view.",
	'Don`t format the drive before you backup the files.',
	'Fax is stranger than fiction.',
	"Give a man a fish and you feed him for a day; Teach him to use the Net and he won't bother you for weeks.",
	'Great groups from little icons grow.',
	'Home is where you hang your @.',
	'Modulation in all things.',
	'Oh, what a tangled web site we weave when first we practice.',
	'Pentium wise, pen and paper foolish.',
	'Speak softly and carry a cellular phone.',
	'The e-mail of the species is more deadly than the mail.',
	'The geek shall inherit the earth.',
	'The modem is the message.',
	"There's many a slip 'twixt the dock and the ship.",
	'Too many clicks spoil the browse.',
	'Virtual reality is its own reward.',
	'What boots up must come down.',
	'Windows will never cease.',
	"You can't teach a new mouse old clicks.",
	"If at first you don't succeed, skydiving is not for you.",
	'Winners never quit, quitters never win.',
	'You snooze, you lose.',
	'Never test the depth of the water with both feet.',
	"If you tell the truth, you don't have to remember anything.",
	'A closed mouth gathers no foot.',
	"You aren't learning much when your lips are moving.",
	"Experience is something you don't get until just after you need it.",
	'A hair on the head is worth two in the brush',
	"An ear that doesn't heed to advice is chopped off together with the head.",
	'The death of a cow marks celebration to even a dying dog.',
	"You learn by looking and listening as opposed to talking. That's why you have two ears, two eyes, and only one mouth."
];
const ball = [
	'It is certain',
	'It is decidedly so',
	'Without a doubt',
	'Yes definitely',
	'You may rely on it',
	'As I see it, yes',
	'Most likely',
	'Outlook good',
	'Yes',
	'Signs point to yes',
	'b1nzy says yes',
	'Reply hazy try again',
	'Ask again later',
	'Better not tell you now',
	'Cannot predict now',
	'Concentrate and ask again',
	'b1nzy is unavailable',
	"Don't count on it",
	'My reply is no',
	'My sources say no',
	'Outlook not so good',
	'Very doubtful',
	'b1nzy will ban you for this'
];
const parker = [
	'https://i.ytimg.com/vi/aOT_bG-vWyg/maxresdefault.jpg',
	'https://i.ytimg.com/vi/OWCAlJ1vsqc/maxresdefault.jpg',
	'https://i.ytimg.com/vi/z6jMU-AwX34/maxresdefault.jpg',
	'https://i.ytimg.com/vi/pF8goco4ix0/maxresdefault.jpg',
	'https://i.ytimg.com/vi/DelH1S32dOg/maxresdefault.jpg',
	'https://i.ytimg.com/vi/3GJUM6pCpew/maxresdefault.jpg',
	'https://i.ytimg.com/vi/CCuaWqhVvIc/maxresdefault.jpg',
	'https://i.ytimg.com/vi/5Yy_unGaD-w/maxresdefault.jpg',
	'https://i.ytimg.com/vi/-9FWBaWah28/maxresdefault.jpg',
	'https://i.ytimg.com/vi/xVBOlbjiHGI/maxresdefault.jpg',
	'https://i.ytimg.com/vi/ggH8cKcPOHI/maxresdefault.jpg',
	'https://i.ytimg.com/vi/_o0cIpLQApk/maxresdefault.jpg',
	'https://i.ytimg.com/vi/aHU-L3BLd_w/maxresdefault.jpg',
	'https://i.ytimg.com/vi/8pSLffliCk0/maxresdefault.jpg',
	'https://i.ytimg.com/vi/HrRMnzANHHs/maxresdefault.jpg',
	'https://i.ytimg.com/vi/hoh4TmPzu1w/maxresdefault.jpg',
	'https://i.ytimg.com/vi/qMP7_IQpSN0/maxresdefault.jpg',
	'https://i.ytimg.com/vi/qkt_wmRKYNQ/maxresdefault.jpg',
	'https://i.ytimg.com/vi/owVwjr6pTqc/maxresdefault.jpg',
	'https://i.ytimg.com/vi/V3uNDe_i_1Y/maxresdefault.jpg',
	'https://i.ytimg.com/vi/-u-O_2Hz82I/maxresdefault.jpg',
	'https://i.ytimg.com/vi/9KABcmczPdg/maxresdefault.jpg',
	'https://i.ytimg.com/vi/q5ozBnrd5Zc/maxresdefault.jpg',
	'https://i.ytimg.com/vi/SOgn6J12NWE/maxresdefault.jpg',
	'https://i.ytimg.com/vi/07PBcmGozDA/maxresdefault.jpg',
	'https://i.ytimg.com/vi/Quwvw0vYkRA/maxresdefault.jpg',
	'https://i.ytimg.com/vi/W1OkVkq2vFM/maxresdefault.jpg',
	'https://i.ytimg.com/vi/pOx_daJT_8c/maxresdefault.jpg',
	'https://i.ytimg.com/vi/g7TGA-EzBHM/maxresdefault.jpg',
	'https://i.ytimg.com/vi/ieUvzy6rnnw/maxresdefault.jpg',
	'https://i.ytimg.com/vi/qYAdXm69l8g/maxresdefault.jpg',
	'https://i.ytimg.com/vi/G_OuIVOGDr8/hqdefault.jpg',
	'https://i.ytimg.com/vi/ryFvH4Ejaxo/maxresdefault.jpg',
	'https://i.ytimg.com/vi/0JTYfMP-yCI/maxresdefault.jpg',
	'https://i.ytimg.com/vi/nv0Onj3wXCE/maxresdefault.jpg',
	'https://i.ytimg.com/vi/T6A0v3xYl7k/maxresdefault.jpg',
	'https://i.ytimg.com/vi/wyl-V0mrEio/maxresdefault.jpg',
	'https://i.ytimg.com/vi/ZbKYmfjMPVM/maxresdefault.jpg',
	'https://i.ytimg.com/vi/tlpYjrbujG0/maxresdefault.jpg',
	'https://i.ytimg.com/vi/XPIgR89jv3Q/maxresdefault.jpg',
	'https://i.ytimg.com/vi/q8n15q1v4Xo/maxresdefault.jpg',
	'https://i.ytimg.com/vi/OEMA6jhi5Qo/maxresdefault.jpg',
	'https://i.ytimg.com/vi/T0xKHwQH-4I/maxresdefault.jpg',
	'https://i.ytimg.com/vi/ZPv1UV0rD8U/maxresdefault.jpg',
	'https://i.ytimg.com/vi/_s5RFgd59ao/maxresdefault.jpg',
	'https://i.ytimg.com/vi/lNuPy-r1GuQ/maxresdefault.jpg',
	'https://i.ytimg.com/vi/ZNiRzZ66YN0/hqdefault.jpg',
	'https://i.ytimg.com/vi/99stb2mzspI/maxresdefault.jpg',
	'https://i.ytimg.com/vi/HuKl3XuEmj4/maxresdefault.jpg',
	'https://i.ytimg.com/vi/Fmb3TCvlETk/hqdefault.jpg',
	'https://i.ytimg.com/vi/JJQWtGm3eIs/maxresdefault.jpg',
	'https://i.ytimg.com/vi/l7lP9y7Bb5g/hqdefault.jpg',
	'https://i.ytimg.com/vi/BRRolKTlF6Q/hqdefault.jpg',
	'https://i.ytimg.com/vi/XPIgR89jv3Q/maxresdefault.jpg',
	'https://cdn.discordapp.com/attachments/110373943822540800/353611070717558784/mattparker_2207234b.png',
	'https://cdn.discordapp.com/attachments/110373943822540800/353611567134277642/MattParkernumberninjacropped.png',
	'http://i.imgur.com/df1an2D.jpg'
];

module.exports = [
	{
		names: [
			'cookie'
		],
		command: (message) => {
			message.channel.createMessage(select(cookie));
		}
	}, {
		names: [
			'proverb'
		],
		command: (message) => {
			message.channel.createMessage(select(proverb));
		}
	}, {
		names: [
			'8ball',
			'magic8',
			'8'
		],
		command: (message) => {
			message.channel.createMessage(select(ball));
		}
	}, {
		names: [
			'parker'
		],
		command: (message) => {
			message.channel.createMessage(select(parker));
		}
	}
];
